trigger:
  - main

pool:
  name: Default
  demands: agent.name
  vmImage: 'ubuntu-latest'

stages:
  - stage: Nodejs
    displayName: Set Up NodeJs
    jobs:
    - job:
      steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '16.x'
          checkLatest: true
          
  - stage:
    displayName: Install Dependencies
    jobs:
      - job:
        steps:
        - script: npm install
        

    
