trigger:
  - main

pool:
  name: Default
  demands: agent.name
  vmImage: 'ubuntu-latest'

stages:
  - stage: Nodejs
    displayName: Set Up NodeJs
    jobs:
    - job:
      steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '16.x'
          checkLatest: true
        displayName: 'Set Up NodeJS'

      - script: npm install
        displayName: 'Install Dependencies'
  
      - script: npm run build
        displayName: 'Build Project'

      - script: npm test -- --all
        displayName: 'Run Tests'
        

    
